### PR TITLE
Functional XML serialization

### PR DESCRIPTION
**Pull request by dsheets**
`DocOckXmlPrint` no longer requires use of `Xmlm.output` or has side effects; it has been renamed `DocOckXmlFold`.

### CODE REVIEW

**Comment by lpw25** [comment]
I like the general idea, but I think we can make the interface more consistent. I think something like:

```ocaml
type 'a fold = { fold: 'b. ('b -> Xmlm.signal -> 'b) -> 'b -> 'a -> 'b }

val unit: 'a fold -> 'a DocOckTypes.Unit.t fold

val file: 'a fold -> 'a DocOckTypes.Unit.t fold
```

and we should also change the parser into an unfold operation for consistency:


```ocaml
type 'a result =
  | Ok of 'a
  | Error of Xmlm.pos option * Xmlm.pos * string

type 'a unfold = { fold: 'b. ('b -> Xmlm.signal result * 'b) -> 'b -> 'a result  * 'b }

val unit: 'a unfold -> 'a DocOckTypes.Unit.t unfold

val file: 'a fold -> 'a DocOckTypes.Unit.t fold
```

This removes the abstract type `'a parser`, which was intended to encourage partial application (by encouraging people to only use `build` once for multiple calls to `file`/`unit`). The new interface should also encourage such partial application (by encouraging people to use `file` once for multiple calls to the resulting unfold).

This interface would also not check that parsing a `file` parsed up to the end of the file, since there is no `Xmlm.signal` for `EOF`, but this is probably not important and could easily be checked by users of the interface.

**Comment by dsheets** [comment]
I don't understand why the accumulator type is universally quantified. I think with that type, it is difficult to actually use the accumulator.

How about:

```ocaml
type ('r,'acc) t = ('acc -> Xmlm.signal -> 'acc) -> 'acc -> 'r -> 'acc

val unit: ('r,'acc) t -> ('r DocOckTypes.Unit.t, 'acc) t

val file: ('r,'acc) t -> ('r DocOckTypes.Unit.t, 'acc) t
```

I'd like to defer the unfold modification for now (and track it in an issue).

**Comment by dsheets** [comment]
Updated.

**Comment by lpw25** [comment]
> I don't understand why the accumulator type is universally quantified. I think with that type, it is difficult to actually use the accumulator.

Because a fold should be polymorphic in the type of its accumulator. I don't see how it would be difficult to use, for example a simple `string fold` looks like:

```ocaml
let string =
{ fold = fun k acc s -> k acc (`Data s) }
```

or placing the string in a tag:

```ocaml
let tagged_string =
    { fold =
      fun k acc s ->
        let acc = k acc (`El_start(("foo", "bar"), [])) in
        let acc = k acc (`Data s) in
          k acc `El_end };;
```

**Comment by dsheets** [comment]
The user of the library will definitely want to use folds that are *not* polymorphic in their accumulator; they want to manipulate a specific accumulator type!

I think the confusion here is between the fold recursion scheme skeleton (should be polymorphic in accumulator) and the fold argument function (should be instantiated to a specific type, i.e. `Xmlm.signal list` so that we can use `::` on it during the fold).

It seems to me that the argument root fold function is a skeleton and could have the quantification but the overall fold function should be polymorphic over both root and accumulator types. I'm not really clear on what the enforcement of the polymorphism is gaining us, though. What if a user wants their root serializer to use special knowledge of the accumulator? Even if they don't, what is wrong with using normal parametric polymorphism?

**Comment by dsheets** [comment]
Ah, I see the quantification gets removed during projection and it works as expected.

I guess it comes down to awkwardness of record expression vs. safety of universal polymorphism...

**Comment by dsheets** [comment]
Actually, I'm not even sure what additional safety is afforded. What does the universal record field disallow that normal parametric polymorphism allows?

I've removed the now unused `DocOckXml` module.

**Comment by lpw25** [comment]
If the fold is not polymorphic then the accumulator type for the outputs of `file` and `unit` are forced to be equal to the accumulator of the inputs. This makes it difficult to implement a robust `unfold` because you want to only pass part of the stream to the `root` fold -- the part between two `base` tags -- without giving it access to the rest of the stream.

I also *want* the slight awkwardness of record syntax, to encourage people to call `DocOckXmlUnfold.file` once to create a record, and then reuse that record for all their unfolding needs. This is because is there is a noticeable cost to setting up the parser, and I would like people not to re-setup the parser for every file they parse.

**Comment by lpw25** [comment]
I also just think that the polymorphic version is more correct.

A function of type:

```ocaml
'b. ('b -> Xmlm.signal -> 'b) -> 'b -> 'a -> 'b
```

is -- by parametricity -- a function that turns an 'a into a stream of xmlm signals.

Wheres a function of type

```ocaml
(foo -> Xmlm.signal -> foo) -> foo -> 'a -> foo
```

is just some function that returns a `foo`.

**Comment by dsheets** [comment]
I sort of see what you are getting at regarding locality for the root function. It makes sense to make the root fold as tightly constrained as possible to make `unfold` sane (fold skeleton is always parametric and when it's rhs, it should be enforced).

I'm not clear on how your record approach is different/better for the general signature, though.

Doesn't
```ocaml
type 'r t = { f : 'acc. ('acc -> Xmlm.signal -> 'acc) -> 'acc -> 'r -> 'acc }

val unit: 'r t -> ('acc -> Xmlm.signal -> 'acc) -> 'acc -> 'r -> 'acc
```
enforce the same constraint?

**Comment by lpw25** [comment]
> Doesn't [...] enforce the same constraint?

It does, but I prefer the one that uses the record for both because the type `'a fold -> 'a t fold` makes clear that you are lifting a fold on `'a` into a fold on `'a t`.

As I said, I also want the awkwardness of the record, so that people are encouraged to write:

```ocaml
let unfold_root = ...

let unfold_file = (DocOckUnfold.file unfold_root).unfold

let x = unfold_file ...
let y = unfold_file ...
let z = unfold_file ...
```

rather than

```ocaml
let unfold_root = ...

let x = DocOckUnfold.file unfold_root ...
let y = DocOckUnfold.file unfold_root ...
let z = DocOckUnfold.file unfold_root ...
```

because the way Menhir handles parameterised parsers means that `DocOckUnfold.file` is needes to setup the parser from scratch (e.g. create a new hashtbl of keywords). (This is the problem with currying, it is hard to distinguish a partial application from a function which does significant work and returns a function).

**Comment by dsheets** [comment]
Ok. That all makes sense. Check out the new commit and then I'll do the unfold.

**Comment by lpw25** [comment]
At this point I'm just nitpicking, but would you mind if the `base` parameters within DocOckFold.ml were passed around as type `'a t` and then projected when they are used (in `identifier_p`) rather than projected out by `unit_p` and `file_p`. I suspect this will be more consistent with how the unfolding code will look.

**Comment by lpw25** [comment]
Also, I think the wrapping up of `unit` and `file` in a record would be better done as part of the lines:

```ocaml
let unit = unit_p
let file = file_p
```

**Comment by lpw25** [comment]
With the above two changes, it should be very easy to expose more of the internal folds (e.g. identifier) later on.

**Comment by lpw25** [comment]
I'm going to go ahead and merge this as is, and then make those last two suggested changes myself.

Thanks very much for this. It is a great improvement on what was there before.

**Comment by dsheets** [comment]
I agree with your nits. I just got lazy. Thanks. :-)

**Comment by lpw25** [comment]
Nits fixed.

**Pull request merged**
